//get a place 
GET http://localhost:5000/users/ 

###
//get a place 
POST http://localhost:5000/admin/ 
Content-Type: application/json

{
        "name": "Sachin",
        "password" : "124"
}

###
//create a place 
POST http://localhost:5000/users/ 
Content-Type: application/json

{
        "name":"Sac",
        "email":"demo@gmail.com",
        "password":"1234",
        "role" : "user"
}
